/**
 * Verified Coimbatore Educational Institutions Knowledge Base
 * Follows the strict College Data Model.
 *
 * Current Academic Year: 2026 / 2026-27
 * Note: Unknown values remain null/undefined. No fabricated data, cutoffs, or fees.
 */

const COIMBATORE_COLLEGES = [
  {
    collegeName: 'PSG College of Technology',
    shortName: 'PSG Tech',
    aliases: ['psg tech', 'psg technology', 'psg engineering', 'psg cse'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Government-Aided Autonomous Engineering College',
    officialWebsite: 'https://www.psgtech.edu',
    affiliation: 'Anna University',
    accreditation: ['NAAC A+ Grade', 'NBA Accredited Programs', 'AICTE Approved'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.Tech Information Technology',
      'B.Tech Artificial Intelligence and Data Science',
      'B.E. Electronics and Communication Engineering',
      'B.E. Electrical and Electronics Engineering',
      'B.E. Mechanical Engineering',
      'B.E. Civil Engineering',
      'B.E. Biomedical Engineering',
      'B.E. Production Engineering',
      'B.Tech Biotechnology',
      'B.Tech Textile Technology',
    ],
    pgCourses: [
      'M.E. Computer Science and Engineering',
      'M.E. VLSI Design',
      'M.E. Embedded and Real-Time Systems',
      'M.E. Structural Engineering',
      'MBA (Master of Business Administration)',
      'MCA (Master of Computer Applications)',
    ],
    phdPrograms: ['Engineering and Technology', 'Computer Science', 'Management Sciences'],
    admissionMode: 'TNEA (Tamil Nadu Engineering Admissions) for UG; TANCET / CEETA-PG / GATE for PG',
    eligibility: [
      'UG: Passed 10+2 with Physics, Chemistry, and Mathematics (Tamil Nadu DOTE norms)',
      'PG: Relevant Bachelor degree with valid TANCET / GATE score',
    ],
    applicationUrl: 'https://www.psgtech.edu/admissions.php',
    admissionOpen: null, // Verified dynamically from official site
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.psgtech.edu', 'https://www.tneaonline.org'],
    notes: 'One of the oldest and most established engineering institutions in Coimbatore (established in 1951).',
  },
  {
    collegeName: 'PSG College of Arts and Science',
    shortName: 'PSG CAS',
    aliases: ['psg cas', 'psg arts', 'psg arts and science', 'psg bca', 'psg bsc'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Government-Aided Autonomous Arts and Science College',
    officialWebsite: 'https://www.psgcas.ac.in',
    affiliation: 'Bharathiar University',
    accreditation: ['NAAC A++ Grade (4th Cycle)', 'UGC Recognized College with Potential for Excellence'],
    ugCourses: [
      'B.C.A. (Bachelor of Computer Applications)',
      'B.Sc. Computer Science',
      'B.Sc. Information Technology',
      'B.Sc. Data Science',
      'B.Com (General, Computer Applications, Corporate Secretaryship, Professional Accounting, Finance)',
      'B.B.A. (Bachelor of Business Administration)',
      'B.Sc. Mathematics',
      'B.Sc. Physics',
      'B.Sc. Chemistry',
      'B.Sc. Biotechnology',
      'B.A. English Literature',
      'B.A. Economics',
    ],
    pgCourses: [
      'M.C.A. (Master of Computer Applications)',
      'M.Sc. Computer Science',
      'M.Sc. Applied Psychology',
      'M.Com',
      'M.A. English Literature',
      'MSW (Master of Social Work)',
    ],
    phdPrograms: ['Arts, Science, Commerce, and Management disciplines'],
    admissionMode: 'Direct Merit-based Online Application via official PSG CAS portal based on Class 12 marks',
    eligibility: ['UG: Passed 10+2 from a recognized board with required subject prerequisites'],
    applicationUrl: 'https://www.psgcas.ac.in/admissions.php',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.psgcas.ac.in'],
    notes: 'Autonomous college affiliated with Bharathiar University, Civil Aerodrome Post, Coimbatore.',
  },
  {
    collegeName: 'Coimbatore Institute of Technology',
    shortName: 'CIT',
    aliases: ['cit', 'cit coimbatore', 'coimbatore institute of technology'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Government-Aided Autonomous Engineering College',
    officialWebsite: 'https://www.cit.edu.in',
    affiliation: 'Anna University',
    accreditation: ['NAAC A Grade', 'NBA Accredited Programs', 'AICTE Approved'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.Tech Information Technology',
      'B.Tech Artificial Intelligence and Data Science',
      'B.E. Electronics and Communication Engineering',
      'B.E. Electrical and Electronics Engineering',
      'B.E. Mechanical Engineering',
      'B.E. Civil Engineering',
      'B.Tech Chemical Engineering',
      '5-Year Integrated M.Sc. Software Systems',
      '5-Year Integrated M.Sc. Data Science',
      '5-Year Integrated M.Sc. Artificial Intelligence and Machine Learning',
    ],
    pgCourses: [
      'M.E. Computer Science and Engineering',
      'M.E. Embedded and Real-Time Systems',
      'M.E. Applied Electronics',
      'M.E. Structural Engineering',
      'MBA',
      'MCA',
    ],
    phdPrograms: ['Engineering, Science, and Humanities'],
    admissionMode: 'TNEA for B.E./B.Tech; CIT Entrance Exam/Marks for 5-Year Integrated M.Sc.; TANCET for PG',
    eligibility: ['10+2 with PCM for engineering degrees'],
    applicationUrl: 'https://www.cit.edu.in/admissions',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.cit.edu.in', 'https://www.tneaonline.org'],
    notes: 'Located at Civil Aerodrome Post, Peelamedu, Coimbatore. Established in 1956.',
  },
  {
    collegeName: 'Government College of Technology',
    shortName: 'GCT',
    aliases: ['gct', 'gct coimbatore', 'govt college of technology'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Government Engineering College (Autonomous)',
    officialWebsite: 'https://gct.ac.in',
    affiliation: 'Anna University',
    accreditation: ['NAAC Accredited', 'NBA Accredited Programs', 'AICTE Approved'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.Tech Information Technology',
      'B.E. Electronics and Communication Engineering',
      'B.E. Electrical and Electronics Engineering',
      'B.E. Electronics and Instrumentation Engineering',
      'B.E. Mechanical Engineering',
      'B.E. Civil Engineering',
      'B.Tech Industrial Biotechnology',
      'B.E. Production Engineering',
    ],
    pgCourses: [
      'M.E. Computer Science and Engineering',
      'M.E. Applied Electronics',
      'M.E. Power Electronics and Drives',
      'M.E. Structural Engineering',
      'M.E. Environmental Engineering',
    ],
    phdPrograms: ['Doctoral research programs affiliated with Anna University'],
    admissionMode: '100% Government Quota via TNEA counselling for B.E./B.Tech',
    eligibility: ['Passed 10+2 with PCM via TNEA Tamil Nadu single window counselling'],
    applicationUrl: 'https://www.tneaonline.org',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://gct.ac.in', 'https://www.tneaonline.org'],
    notes: 'Premier state government engineering college located at Thadagam Road, Coimbatore. Established in 1945.',
  },
  {
    collegeName: 'Kumaraguru College of Technology',
    shortName: 'KCT',
    aliases: ['kct', 'kct coimbatore', 'kumaraguru', 'kumaraguru college'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Private Autonomous Engineering College',
    officialWebsite: 'https://www.kct.ac.in',
    affiliation: 'Anna University',
    accreditation: ['NAAC A++ Grade', 'NBA Accredited Programs', 'AICTE Approved'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.Tech Information Technology',
      'B.Tech Artificial Intelligence and Data Science',
      'B.E. Electronics and Communication Engineering',
      'B.E. Electrical and Electronics Engineering',
      'B.E. Mechanical Engineering',
      'B.E. Mechatronics Engineering',
      'B.E. Civil Engineering',
      'B.Tech Biotechnology',
      'B.Tech Fashion Technology',
      'B.Tech Textile Technology',
    ],
    pgCourses: [
      'M.E. Computer Science and Engineering',
      'M.E. Communication Systems',
      'M.E. Embedded Systems Technologies',
      'MBA',
      'MCA',
    ],
    phdPrograms: ['Recognized research centres by Anna University'],
    admissionMode: 'TNEA counselling (Government quota) and Management Quota',
    eligibility: ['10+2 with Physics, Chemistry, and Mathematics'],
    applicationUrl: 'https://admissions.kct.ac.in',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.kct.ac.in'],
    notes: 'Located at Chinnavedampatti, Saravanampatti, Coimbatore.',
  },
  {
    collegeName: 'Bharathiar University',
    shortName: 'BU',
    aliases: ['bharathiar university', 'bharathiyar university', 'bu coimbatore'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'State Public University',
    officialWebsite: 'https://b-u.ac.in',
    affiliation: 'State University (Affiliates Arts & Science Colleges across Coimbatore, Erode, Tirupur, Nilgiris)',
    accreditation: ['NAAC A++ Grade', 'UGC Recognized', 'NIRF Ranked State University'],
    ugCourses: ['Offered through affiliated colleges'],
    pgCourses: [
      'M.Sc. Computer Science',
      'M.Sc. Information Technology',
      'M.Sc. Data Analytics',
      'M.Sc. Biotechnology',
      'M.Sc. Mathematics',
      'M.Sc. Physics',
      'M.Sc. Chemistry',
      'M.A. English Literature',
      'M.A. Tamil',
      'M.Com (Finance and Computer Applications)',
      'MBA (Master of Business Administration)',
      'MCA (Master of Computer Applications)',
    ],
    phdPrograms: ['Ph.D. and M.Phil across Arts, Science, Commerce, Social Work, Management'],
    admissionMode: 'Direct Entrance Exam & Merit based admission for University Departments',
    eligibility: ['Bachelor degree in relevant discipline from a recognized university'],
    applicationUrl: 'https://b-u.ac.in/admissions',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://b-u.ac.in'],
    notes: 'State university established in 1982, located at Maruthamalai Road, Coimbatore.',
  },
  {
    collegeName: 'Anna University Regional Campus Coimbatore',
    shortName: 'AURCC',
    aliases: ['anna university coimbatore', 'aurcc', 'anna university regional campus'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'State University Campus',
    officialWebsite: 'https://aurcc.ac.in',
    affiliation: 'Anna University, Chennai',
    accreditation: ['State University Campus', 'AICTE Approved', 'UGC Recognized'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.Tech Artificial Intelligence and Data Science',
      'B.E. Electronics and Communication Engineering',
      'B.E. Electrical and Electronics Engineering',
      'B.E. Mechanical Engineering',
    ],
    pgCourses: [
      'M.E. Computer Science and Engineering',
      'M.E. VLSI Design',
      'MBA (Master of Business Administration)',
    ],
    phdPrograms: ['Doctoral research programs under Anna University regulations'],
    admissionMode: 'TNEA counselling for UG; TANCET / CEETA-PG for PG',
    eligibility: ['10+2 with PCM through TNEA single window counselling'],
    applicationUrl: 'https://www.tneaonline.org',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://aurcc.ac.in', 'https://www.tneaonline.org'],
    notes: 'Located at Maruthamalai Main Road, Somayampalayam, Coimbatore.',
  },
  {
    collegeName: 'Tamil Nadu Agricultural University',
    shortName: 'TNAU',
    aliases: ['tnau', 'tnau coimbatore', 'agriculture college coimbatore', 'agri college'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'State Public Agricultural University',
    officialWebsite: 'https://tnau.ac.in',
    affiliation: 'State Agricultural University',
    accreditation: ['ICAR Accredited', 'UGC Recognized'],
    ugCourses: [
      'B.Sc. (Hons.) Agriculture',
      'B.Sc. (Hons.) Horticulture',
      'B.Sc. (Hons.) Forestry',
      'B.Sc. (Hons.) Sericulture',
      'B.Sc. (Hons.) Agri-Business Management',
      'B.Tech Agricultural Engineering',
      'B.Tech Biotechnology',
      'B.Tech Food Technology',
    ],
    pgCourses: [
      'M.Sc. Agriculture (Agronomy, Plant Breeding, Soil Science, Entomology, etc.)',
      'M.Sc. Horticulture',
      'M.Tech Agricultural Engineering',
    ],
    phdPrograms: ['Doctoral research in all Agricultural disciplines'],
    admissionMode: 'Online counselling by TNAU based on Class 12 marks (PCB/PCM)',
    eligibility: ['10+2 with Physics, Chemistry, Biology / Mathematics'],
    applicationUrl: 'https://tnau.ucanapply.com',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://tnau.ac.in'],
    notes: 'Premier agricultural institution established in 1971, located at Lawley Road, Coimbatore.',
  },
  {
    collegeName: 'Amrita Vishwa Vidyapeetham (Coimbatore Campus)',
    shortName: 'Amrita University',
    aliases: ['amrita', 'amrita university', 'amrita coimbatore', 'amrita ettimadai'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Deemed-to-be University (Private)',
    officialWebsite: 'https://www.amrita.edu',
    affiliation: 'Deemed University',
    accreditation: ['NAAC A++ Grade', 'UGC Recognized', 'NIRF Top Ranked University'],
    ugCourses: [
      'B.Tech Computer Science and Engineering',
      'B.Tech Artificial Intelligence and Data Science',
      'B.Tech Computer Science and Engineering (Cyber Security)',
      'B.Tech Electronics and Communication Engineering',
      'B.Tech Electrical and Computer Engineering',
      'B.Tech Mechanical Engineering',
      'B.Tech Aerospace Engineering',
      'B.Tech Chemical Engineering',
      'B.Tech Civil Engineering',
    ],
    pgCourses: [
      'M.Tech Artificial Intelligence',
      'M.Tech Cyber Security',
      'M.Tech VLSI Design',
      'M.Tech Data Science',
      'MBA (Amrita School of Business)',
      'MCA',
    ],
    phdPrograms: ['PhD in Engineering, Computing, Sciences, Management'],
    admissionMode: 'AEEE (Amrita Entrance Examination - Engineering) / JEE Main percentile',
    eligibility: ['Minimum 60% in 10+2 with PCM for B.Tech'],
    applicationUrl: 'https://www.amrita.edu/admissions',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.amrita.edu'],
    notes: 'Headquarters campus located at Ettimadai, Coimbatore.',
  },
  {
    collegeName: 'Avinashilingam Institute for Home Science and Higher Education for Women',
    shortName: 'Avinashilingam University',
    aliases: ['avinashilingam', 'avinashilingam university', 'avinashilingam institute'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Deemed-to-be University (Women Only)',
    officialWebsite: 'https://avinuty.ac.in',
    affiliation: 'Deemed University',
    accreditation: ['NAAC A++ Grade', 'UGC Recognized', 'AICTE Approved for Engineering'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.E. Artificial Intelligence and Data Science',
      'B.E. Biomedical Instrumentation Engineering',
      'B.Sc. Home Science, Food Science and Nutrition',
      'B.C.A.',
      'B.Sc. Computer Science',
      'B.Com',
      'B.B.A.',
    ],
    pgCourses: ['M.E. Computer Science', 'M.Sc. Food Science and Nutrition', 'MBA', 'MCA', 'M.Ed'],
    phdPrograms: ['Doctoral degrees in Home Science, Science, Humanities, Engineering'],
    admissionMode: 'Merit based online application / CUET / University entrance',
    eligibility: ['Female candidates who passed 10+2 with requisite subjects'],
    applicationUrl: 'https://avinuty.ac.in/admission',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://avinuty.ac.in'],
    notes: 'Exclusively for women. Main campus at Bharathi Park Road, Faculty of Engineering campus at Varapalayam, Thadagam Post.',
  },
  {
    collegeName: 'Karunya Institute of Technology and Sciences',
    shortName: 'Karunya University',
    aliases: ['karunya', 'karunya university', 'karunya institute'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Deemed-to-be University (Private)',
    officialWebsite: 'https://www.karunya.edu',
    affiliation: 'Deemed University',
    accreditation: ['NAAC A++ Grade', 'UGC Recognized', 'AICTE Approved'],
    ugCourses: [
      'B.Tech Computer Science and Engineering',
      'B.Tech Artificial Intelligence and Machine Learning',
      'B.Tech Biotechnology',
      'B.Tech Biomedical Engineering',
      'B.Tech Aerospace Engineering',
      'B.Tech Electronics and Communication Engineering',
      'B.Tech Mechanical Engineering',
      'B.Sc. (Hons.) Agriculture',
    ],
    pgCourses: ['M.Tech programs, MBA, MCA, M.Sc. Agriculture'],
    phdPrograms: ['Engineering, Science, Agriculture, Management'],
    admissionMode: 'KEE (Karunya Entrance Examination) / Merit / JEE Main',
    eligibility: ['Passed 10+2 with minimum required percentage in PCM/PCB'],
    applicationUrl: 'https://admissions.karunya.edu',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.karunya.edu'],
    notes: 'Located at Karunya Nagar, Siruvani Main Road, Coimbatore.',
  },
  {
    collegeName: 'Karpagam Academy of Higher Education',
    shortName: 'Karpagam University',
    aliases: ['karpagam', 'karpagam university', 'karpagam academy'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Deemed-to-be University (Private)',
    officialWebsite: 'https://kahedu.edu.in',
    affiliation: 'Deemed University',
    accreditation: ['NAAC A+ Grade', 'UGC Recognized', 'AICTE Approved', 'COA Approved'],
    ugCourses: [
      'B.Tech Computer Science and Engineering',
      'B.Tech Artificial Intelligence and Data Science',
      'B.Arch (Bachelor of Architecture)',
      'B.C.A.',
      'B.Sc. Computer Science',
      'B.Com',
      'B.B.A.',
      'B.Pharm (Pharmacy)',
    ],
    pgCourses: ['M.Tech, MBA, MCA, M.Arch, M.Pharm, M.Sc.'],
    phdPrograms: ['Doctoral research across Engineering, Architecture, Pharmacy, Science'],
    admissionMode: 'University online application / NATA for B.Arch / Merit based',
    eligibility: ['Passed 10+2 from recognized board'],
    applicationUrl: 'https://kahedu.edu.in/admissions',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://kahedu.edu.in'],
    notes: 'Located at Pollachi Main Road, Eachanari, Coimbatore.',
  },
  {
    collegeName: 'Sri Krishna College of Engineering and Technology',
    shortName: 'SKCET',
    aliases: ['skcet', 'sri krishna engineering', 'sri krishna college of engineering'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Private Autonomous Engineering College',
    officialWebsite: 'https://www.skcet.ac.in',
    affiliation: 'Anna University',
    accreditation: ['NAAC A Grade', 'NBA Accredited Programs', 'AICTE Approved'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.Tech Information Technology',
      'B.Tech Artificial Intelligence and Data Science',
      'B.Tech Computer Science and Business Systems (TCS Collab)',
      'B.E. Electronics and Communication Engineering',
      'B.E. Electrical and Electronics Engineering',
      'B.E. Mechanical Engineering',
      'B.E. Mechatronics Engineering',
      'B.E. Civil Engineering',
    ],
    pgCourses: ['M.E. Computer Science and Engineering', 'M.E. Applied Electronics', 'MBA', 'MCA'],
    phdPrograms: ['Anna University recognized research centres'],
    admissionMode: 'TNEA counselling (Government quota) & Management Quota',
    eligibility: ['10+2 with Physics, Chemistry, and Mathematics'],
    applicationUrl: 'https://www.skcet.ac.in/admissions',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.skcet.ac.in'],
    notes: 'Located at Kuniamuthur, Coimbatore.',
  },
  {
    collegeName: 'Sri Krishna Arts and Science College',
    shortName: 'SKASC',
    aliases: ['skasc', 'sri krishna arts', 'sri krishna arts and science'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Private Autonomous Arts and Science College',
    officialWebsite: 'https://www.skasc.ac.in',
    affiliation: 'Bharathiar University',
    accreditation: ['NAAC A Grade', 'Autonomous', 'AICTE Approved for MBA/MCA'],
    ugCourses: [
      'B.C.A. (Bachelor of Computer Applications)',
      'B.Sc. Computer Science',
      'B.Sc. Information Technology',
      'B.Sc. Computer Science with Cognitive Systems',
      'B.Com (General, Professional Accounting, Corporate Secretaryship)',
      'B.B.A.',
      'B.Sc. Biotechnology',
    ],
    pgCourses: ['M.C.A.', 'M.Sc. Computer Science', 'M.Com', 'MSW', 'MBA'],
    phdPrograms: ['Commerce, Computer Science, Management'],
    admissionMode: 'Direct online application based on Class 12 marks',
    eligibility: ['Passed 10+2 from recognized board'],
    applicationUrl: 'https://www.skasc.ac.in/admission',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.skasc.ac.in'],
    notes: 'Located at Sugunapuram, Kuniamuthur, Coimbatore.',
  },
  {
    collegeName: 'Sri Ramakrishna Engineering College',
    shortName: 'SREC',
    aliases: ['srec', 'sri ramakrishna engineering', 'ramakrishna engineering'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'Private Autonomous Engineering College',
    officialWebsite: 'https://www.srec.ac.in',
    affiliation: 'Anna University',
    accreditation: ['NAAC A+ Grade', 'NBA Accredited Programs', 'AICTE Approved'],
    ugCourses: [
      'B.E. Computer Science and Engineering',
      'B.Tech Information Technology',
      'B.Tech Artificial Intelligence and Data Science',
      'B.E. Electronics and Communication Engineering',
      'B.E. Electrical and Electronics Engineering',
      'B.E. Mechanical Engineering',
      'B.E. Biomedical Engineering',
      'B.E. Civil Engineering',
    ],
    pgCourses: ['M.E. Computer Science', 'M.E. VLSI Design', 'MBA'],
    phdPrograms: ['Anna University approved research centres'],
    admissionMode: 'TNEA counselling (Government quota) & Management Quota',
    eligibility: ['10+2 with PCM'],
    applicationUrl: 'https://www.srec.ac.in/admissions',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://www.srec.ac.in'],
    notes: 'Located at Vattamalaipalayam, NGGO Colony Post, Coimbatore.',
  },
  {
    collegeName: 'Government Arts College, Coimbatore',
    shortName: 'GAC Coimbatore',
    aliases: ['gac', 'gac coimbatore', 'govt arts college coimbatore'],
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    institutionType: 'State Government Autonomous Arts and Science College',
    officialWebsite: 'https://gacbe.ac.in',
    affiliation: 'Bharathiar University',
    accreditation: ['NAAC A Grade', 'Autonomous Status', 'UGC Recognized'],
    ugCourses: [
      'B.Sc. Computer Science',
      'B.Sc. Mathematics',
      'B.Sc. Physics',
      'B.Sc. Chemistry',
      'B.Sc. Botany',
      'B.Sc. Zoology',
      'B.Com',
      'B.B.A.',
      'B.A. English Literature',
      'B.A. Tamil Literature',
      'B.A. History',
      'B.A. Economics',
    ],
    pgCourses: [
      'M.Sc. Computer Science',
      'M.Sc. Mathematics',
      'M.Com',
      'M.A. English Literature',
      'M.A. Economics',
      'MCA',
    ],
    phdPrograms: ['Full-time and part-time PhD across science, arts, and commerce departments'],
    admissionMode: 'Tamil Nadu Government Arts and Science Colleges Admission (TNGASA) single window counselling',
    eligibility: ['10+2 with relevant subjects via TNGASA portal (https://www.tngasa.in)'],
    applicationUrl: 'https://www.tngasa.in',
    admissionOpen: null,
    lastUpdated: '2026-01-15T00:00:00Z',
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    sourceUrls: ['https://gacbe.ac.in', 'https://www.tngasa.in'],
    notes: 'Historical government college established in 1852, located at Race Course Road, Coimbatore.',
  },
];

module.exports = {
  COIMBATORE_COLLEGES,
};
